FROM python:3.9

COPY ./requirements.txt ./requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install bitmex
RUN pip3 install dydx_v3_python
RUN pip3 install python-dotenv
RUN pip3 install --no-cache-dir --user -r requirements.txt
RUN pip3 install --upgrade urllib3

RUN mkdir multibot
WORKDIR ./multibot
RUN touch rates.txt
COPY . .

ENV PYTHONPATH="/:$PYTHONPATH"
ENV TZ=Europe/London
