FROM python:3.9

COPY ./requirements.txt ./requirements.txt
RUN pip install --upgrade pip
RUN pip install bitmex
RUN pip3 install dydx_v3_python
RUN pip install python-dotenv
RUN pip install --no-cache-dir --user -r requirements.txt
RUN pip install --upgrade urllib3

RUN mkdir multibot
WORKDIR ./multibot
RUN touch rates.txt
COPY . .

ENV PYTHONPATH="/:$PYTHONPATH"
ENV TZ=Europe/London
